version: 2
jobs:
  build:
    working_directory: ~/circleci-sg
    resource_class: xlarge
    docker:
      - image: "circleci/openjdk:${SG_JAVA_BUILD_VERSION:-11}-jdk-browsers"
    steps:
      - run:
          name: Install and Update
          command: sudo apt-get update -yqq && sudo apt-get install -yqq libapr1 openssl libxml2-utils
      - run:
          name: Versions
          command: 'uname -a;java -version;openssl version'
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v3-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v3-{{ .Branch }}-
            - maven-repo-v3-
      #- run: ./smoketest.sh
      - run: SG_TEST_OPENSSL_OPT=true mvn -U -Pcoverage verify
      - store_test_results:
          path: target/surefire-reports
      - deploy:
          name: Deploy
          command: |
            
            mvn deploy -U -DskipTests -s settings.xml
            
            set +e
            
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              SG_TEST_OPENSSL_OPT=true mvn -U -Pcoverage sonar:sonar -Dsonar.organization=floragunncom-github -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=https://sonarcloud.io
            fi
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v3-{{ .Branch }}-{{ checksum "pom.xml" }}

#workflows:
#  version: 2
#  commit:
#    jobs:
#      - build
#  nightly:
#    triggers:
#      - schedule:
#          cron: "0 1 * * *"
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - build