version: 2
jobs:
  build:
    working_directory: ~/circleci-sg
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - run:
          name: Versions
          command: 'uname -a;java -version;openssl version'
      - checkout
      - restore_cache:
          key: circleci-sg-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-sg-{{ checksum "pom.xml" }}
      - run: ./smoketest.sh
      - run: SG_TEST_OPENSSL_OPT=true mvn -Pcoverage verify
      - store_test_results:
          path: target/surefire-reports
      #- store_artifacts:
      #    path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
      - deploy:
          name: Deploy
          command: |
            
            mvn deploy -DskipTests -s settings.xml
          
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              SG_TEST_OPENSSL_OPT=true mvn -Pcoverage sonar:sonar -Dsonar.organization=floragunncom-github -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=https://sonarcloud.io
            fi

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build